name: build

on:
  push:
    branches:
      - master

env:
  XQT_PLATFORM: 'release'
  GRADLE_VERSION: 8.5

jobs:
  xqt-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Source Code Checkout
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: actions/checkout@v3
        with:
          repository: rhdunn/xqt-platform
          ref: ${{ env.XQT_PLATFORM }}

      - name: Setup JDK ${{ matrix.java }}
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle ${{ env.GRADLE_VERSION }}
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Build for Kotlin/JVM
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: gradle -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: gradle -D jvm.target=${{ matrix.java }} jvmTest

      - name: Publish Kotlin/Multiplatform to Maven Local
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: gradle -D jvm.target=${{ matrix.java }} publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/JVM to Maven Local
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: gradle -D jvm.target=${{ matrix.java }} publishJvmPublicationToMavenLocal

      - name: Tar XQT Platform Artifacts
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: tar -cvf xqt-platform-jvm-${{ matrix.java }}.tar -C ~/.m2/repository/xqt-platform .

      - name: Upload XQT Platform Artifacts
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: actions/upload-artifact@v3
        with:
          name: xqt-platform-jvm-${{ matrix.java }}
          path: xqt-platform-jvm-${{ matrix.java }}.tar

  plugin:
    needs: xqt-platform
    strategy:
      fail-fast: false
      matrix:
        idea-version: [
#            IC-2022.1,
#            IC-2022.2,
#            IC-2022.3,
#            IC-2023.1,
#            IC-2023.2,
#            IC-2023.3,
            IC-2024.1,
#            LATEST-EAP-SNAPSHOT
        ]
        include:
#
#          - java-version: 11
#            idea-version: IC-2022.1
#
#          - java-version: 11
#            idea-version: IC-2022.2
#
#          - java-version: 17
#            idea-version: IC-2022.3
#
#          - java-version: 17
#            idea-version: IC-2023.1
#
#          - java-version: 17
#            idea-version: IC-2023.2

          - java-version: 17
            idea-version: IC-2024.1
#
#          - java-version: 17
#            idea-version: LATEST-EAP-SNAPSHOT

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IDEA_VERSION: ${{ matrix.idea-version }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Download XQT Platform Artifacts
        if: ${{ env.XQT_PLATFORM == 'master' }}
        uses: actions/download-artifact@v3
        with:
          name: xqt-platform-jvm-${{ matrix.java-version }}

      - name: Extract XQT Platform Artifacts to Maven Local
        if: ${{ env.XQT_PLATFORM == 'master' }}
        run: |
          mkdir -p ~/.m2/repository/xqt-platform
          tar -xvf xqt-platform-jvm-${{ matrix.java-version }}.tar -C ~/.m2/repository/xqt-platform

      - name: Build
        run: gradle :assemble

      - name: Run Tests
        run: gradle test

      - name: Build Plugin
        run: gradle buildPlugin

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: xquery-intellij-plugin-${{ matrix.idea-version }}
          path: build/distributions/xquery-intellij-plugin-*.zip
